### ISSUE TITLE
There might be missing information in the readme :)

### ISSUE THREAD

**Issue by ranomier** [freckled-dev/fubble#1]
I build fubble on my small laptop for 2 hours to get this ... :p

![image](https://user-images.githubusercontent.com/7649949/112391851-d350d480-8cf8-11eb-9701-3f87a3c2bada.png)

I'm not mad. But what shall i do?

**Comment by qwertzui11** [comment]
Congratulation you did the first issue! :smile: And it seems, you are the first one to compile it outside our company.

I'll fix the permissions to the base image in the next 24h. Thx for the bug-report!

Did you have any other issues compiling the project? Any suggestions on improving the build-documentation?

**Comment by qwertzui11** [comment]
fixed by https://github.com/freckled-dev/fubble/commit/2b0bddb65b881ab4a0a7ed629fb08ccc7774da82 and merged into master.

I suggest you pull and run `docker-compose up` once more :smile:

**Comment by ranomier** [comment]
Thanks a lot! Nice!
It does work now.

:cookie:
