### ISSUE TITLE
seens like some depencies are not install (for the client)

### ISSUE THREAD

**Issue by ranomier** [freckled-dev/fubble#2]
![image](https://user-images.githubusercontent.com/7649949/112628153-ccc67800-8e32-11eb-87c8-c8d827ff6529.png)

Greetings :)

I hope i don't annoy you guys :) If so just tell me.

I can solve this one for myself and update the needed packages here.

**Comment by ranomier** [comment]
mmmh i used ubuntu 20.04 LTS but it seems that a newer qt version is required:
![image](https://user-images.githubusercontent.com/7649949/112630150-80306c00-8e35-11eb-8bda-b715fd08f366.png)

 
Here a the deps i gathered so far:
![image](https://user-images.githubusercontent.com/7649949/112630370-cb4a7f00-8e35-11eb-91b4-405bc42226f2.png)

**Comment by qwertzui11** [comment]
Ah yes, `fubble` gets build against a newer version of qt than the one in the apt-repos. execute it in bash like this

```bash
LD_LIBRARY_PATH=../fubble_build/qt/5.15.1/gcc_64/lib/ ../fubble_build/install/bin/fubble
```

or like this 

```bash
export LD_LIBRARY_PATH=../fubble_build/qt/5.15.1/gcc_64/lib/
../fubble_build/install/bin/fubble
```

`LD_LIBRARY_PATH` makes the newer shared objects (`*.so`) libs of qt available to fubble. 

Thx for the great issue! I'll improve the README.

**Comment by qwertzui11** [comment]
May I ask what's your goal with fubble? What do you want to achieve with the app/library? :smile:

**Comment by ranomier** [comment]
I want to test it. I have a little community with a few guys.

I also found this:
https://github.com/thecodingmachine/workadventure

looks very interesting but does not have a matrix backend.

**Comment by qwertzui11** [comment]
:+1: 

btw, instead of building it yourself u can use the pre-compiled version from the website https://fubble.io/ :smile: 

the `fubble.appimage` takes the same arguments.
